AUGMENTATION: True
IMAGE_SIZE: [224,224,3] # required by VGG 16 MODEL
BATCH_SIZE: 16
INCLUDE_TOP: False    # only training  a pretrained model 
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01
